---
# tasks file for ansible-gitlab

- include: yum-dependencies.yml
  when: ansible_os_family == "RedHat"

- include: setup-rhel.yml
  when: ansible_os_family == "RedHat"

- include: rhel-postfix.yml
  when: ansible_os_family == "RedHat"

- include: yum-install.yml
  when: ansible_os_family == "RedHat"
